#!/bin/bash

set -e

. /lib/lsb/init-functions

PACKAGES="$@"

log_action_begin_msg "Installing packages: $PACKAGES"

DEBIAN_FRONTEND=noninteractive apt-get install -y $PACKAGES &>> $LOG_DEST

log_action_end_msg $?
