#!/bin/bash

# LSB is wonky with Debian
export TERM=xterm
export LOG_DEST=$(mktemp -t configurate_$(date +%Y%m%d%H%M)_XXXX.log)

. /lib/lsb/init-functions

log_action_msg "configurate starting..."
echo


if [[ -z $1 ]]; then
  log_failure_msg "No Runfile provided"
  exit -1
fi

if [[ $1 == "interactive" ]]; then
  shift
  if [[ -z $* ]]; then
    log_failure_msg "No interactive commands provided"
    exit -1
  fi

  module=$*
  log_action_msg "Running module $module"
  echo "Running module $module" >> $LOG_DEST
  echo "====================" >> $LOG_DEST
  bash modules/$module

  log_action_msg "Module output available at $LOG_DEST"
  exit
fi

RUNLIST=$1

log_action_msg "Module output available at $LOG_DEST"

echo "configurate" > $LOG_DEST
date >> $LOG_DEST
echo "====================" >> $LOG_DEST
echo >> $LOG_DEST

while read -r module; do
    [[ $module = \#* || -z $module ]] && continue

    log_action_msg "Running module $module"
    echo "Running module $module" >> $LOG_DEST
    echo "====================" >> $LOG_DEST
    bash modules/$module
    echo >> $LOG_DEST
done < $RUNLIST

echo "====================" >> $LOG_DEST
echo "End of log" >> $LOG_DEST

