#!/bin/bash

# LSB is wonky with Debian
export TERM=xterm
export LOG_DEST=bootstrap_$(date +%Y%m%d%H%M).log

. /lib/lsb/init-functions

log_action_msg "kotori bootstrapping script"
echo

if [[ -z $1 ]]; then
  log_failure_msg "No Runfile provided"
  exit -1
fi

RUNLIST=$1

echo "kotori bootstrapping script" > $LOG_DEST
date >> $LOG_DEST
echo "====================" >> $LOG_DEST
echo >> $LOG_DEST

while read -r module; do
    [[ $module = \#* || -z $module ]] && continue

    log_action_msg "Running module $module"
    echo "Running module $module" >> $LOG_DEST
    echo "====================" >> $LOG_DEST
    bash modules/$module
    echo >> $LOG_DEST
done < $RUNLIST

log_action_msg "Module output available at $LOG_DEST"
