#!/bin/bash

set -e

. /lib/lsb/init-functions

source ~/perl5/perlbrew/etc/bashrc

VERSION=$1

log_action_begin_msg "Installing Perl $ALIAS"

perlbrew install perl-$VERSION \
    --thread \
    --64all \
    --notest \
    -Duselargefiles \
    -Dcccdlflags=-fPIC \
    -Doptimize=-O2 \
    -Dccflags=-DDEBIAN &>> $LOG_DEST

log_action_end_msg $?
