#!/bin/bash

set -e

. /lib/lsb/init-functions

source ~/perl5/perlbrew/etc/bashrc

PACKAGES="$@"

log_action_begin_msg "Installing packages: $PACKAGES"

cpanm --notest $PACKAGES &>> $LOG_DEST

log_action_end_msg $?
